openapi: 3.0.2
info:
  title: LinearB API
  version: '1.0'
  x-logo:
    url: https://app.linearb.io/static/media/linearb-logo.4f89da9b69ad724c9f8584f316e8112f.svg
servers:
  - url: https://api.linearb-staging-01.io
paths:
  /api/v1/deployments:
    get:
      tags:
        - deployments
      summary: List Deployments
      description: '**List Deployments**'
      operationId: get_deployments_api_v1_deployments_get
      parameters:
        - required: false
          schema:
            title: Repository Id
            type: integer
          name: repository_id
          in: query
        - required: false
          schema:
            title: After
            type: string
          name: after
          in: query
        - required: false
          schema:
            title: Before
            type: string
          name: before
          in: query
        - required: false
          schema:
            title: Limit
            maximum: 100
            exclusiveMinimum: false
            type: integer
            default: 10
          name: limit
          in: query
        - required: false
          schema:
            title: Offset
            minimum: 0
            type: integer
            default: 0
          name: offset
          in: query
        - required: false
          schema:
            title: Stage
            type: string
          name: stage
          in: query
        - required: false
          schema:
            allOf:
              - $ref: '#/components/schemas/DeploymentsSortByEnum'
            default: published_at
          name: sort_by
          in: query
        - required: false
          schema:
            allOf:
              - $ref: '#/components/schemas/DeploymentsSortDirEnum'
            default: desc
          name: sort_dir
          in: query
        - required: false
          schema:
            title: Commit Sha
            type: string
          name: commit_sha
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeploymentsResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
    post:
      tags:
        - deployments
      summary: Create Deployment
      description: '**Create Deployment**'
      operationId: post_deployment_api_v1_deployments_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDeploymentRequestModel'
            examples:
              example1:
                summary: Report release using tag
                description: ''
                value:
                  repo_url: https://github.com/owner/my-repo.git
                  ref_name: v1.20.55
              example2:
                summary: Report release using commit sha
                description: ''
                value:
                  repo_url: https://github.com/owner/my-repo.git
                  ref_name: cf8386c6c92bb24b3e7a48a62cef758d6dbed0ca
              example3:
                summary: Report custom stage
                description: ''
                value:
                  repo_url: https://github.com/owner/my-repo.git
                  ref_name: cf8386c6c92bb24b3e7a48a62cef758d6dbed0ca
                  timestamp: '2022-03-14T22:23:34Z'
                  stage: my_stage
              example4:
                summary: Report custom services
                description: ''
                value:
                  repo_url: https://github.com/owner/my-repo.git
                  ref_name: cf8386c6c92bb24b3e7a48a62cef758d6dbed0ca
                  timestamp: '2022-03-14T22:23:34Z'
                  stage: my_stage
                  services:
                    - service a
                    - service b
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateDeploymentResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/teams/:
    get:
      tags:
        - teams
      summary: Get Teams
      description: Teams API endpoint returns a list of all teams with contributors.
      operationId: get_teams_api_v1_teams__get
      parameters:
        - description: Partial data response flag defines the output schema. If it is False, then will return full teams objects data. Otherwise only mappings for teams, contributors ids and names
          required: false
          schema:
            title: Partial data response flag
            type: boolean
            description: Partial data response flag defines the output schema. If it is False, then will return full teams objects data. Otherwise only mappings for teams, contributors ids and names
            default: true
          name: partial
          in: query
        - description: If True, will return only contributors, that does not have parent contributor. Otherwise, will return only parents and stand-alone contributors
          required: false
          schema:
            title: Non Merged Members Flag
            type: boolean
            description: If True, will return only contributors, that does not have parent contributor. Otherwise, will return only parents and stand-alone contributors
            default: false
          name: nonmerged_members_only
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Teams Api V1 Teams  Get
                anyOf:
                  - $ref: '#/components/schemas/GetTeamsFullResponseModel'
                  - $ref: '#/components/schemas/GetTeamsPartialResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/teams/{team_id}:
    get:
      tags:
        - teams
      summary: Get Team
      description: Teams API endpoint returns a single team with contributors by id.
      operationId: get_team_api_v1_teams__team_id__get
      parameters:
        - description: Team object ID
          required: true
          schema:
            title: Team ID
            type: integer
            description: Team object ID
          name: team_id
          in: path
        - description: Partial data response flag defines the output schema. If it is False, then will return full teams objects data. Otherwise only mappings for teams, contributors ids and names
          required: false
          schema:
            title: Partial data response flag
            type: boolean
            description: Partial data response flag defines the output schema. If it is False, then will return full teams objects data. Otherwise only mappings for teams, contributors ids and names
            default: true
          name: partial
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Team Api V1 Teams  Team Id  Get
                anyOf:
                  - $ref: '#/components/schemas/TeamModel'
                  - $ref: '#/components/schemas/TeamPartialResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Team is not found
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v2/measurements:
    post:
      tags:
        - Measurements V2
      summary: Post Metrics
      description: |-
        Get V2 metrics endpoint

        This API can be used in order to extract metrics data from LinearB on the fly.
        It can be used to retrieve all metrics and for those that are supported,
        the aggregation of p75, p50 and avg can be chosen.
      operationId: post_metrics_api_v2_measurements_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMetricsPayloadModel'
            examples:
              example1:
                summary: Get metrics with time ranges
                description: ''
                value:
                  group_by: organization
                  roll_up: custom
                  requested_metrics:
                    - name: branch.computed.cycle_time
                      agg: p75
                    - name: releases.count
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2022-05-29'
                    - after: '2022-05-30'
                      before: '2022-06-05'
                    - after: '2022-06-06'
                      before: '2022-06-12'
                    - after: '2022-06-13'
                      before: '2022-06-19'
              example2:
                summary: Get metrics with weekly rollup
                description: ''
                value:
                  group_by: organization
                  roll_up: 1w
                  requested_metrics:
                    - name: branch.computed.cycle_time
                      agg: p75
                    - name: branch.computed.cycle_time
                      agg: avg
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2022-06-29'
              example3:
                summary: Get metrics for specific repository
                description: ''
                value:
                  group_by: organization
                  roll_up: 1d
                  repository_ids:
                    - 456801317
                    - 1235235
                  requested_metrics:
                    - name: branch.time_to_prod
                      agg: p50
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2022-06-29'
              example4:
                summary: Get metrics for specific teams
                description: ''
                value:
                  group_by: team
                  roll_up: 1mo
                  team_ids:
                    - 5273
                    - 58
                  requested_metrics:
                    - name: branch.time_to_prod
                      agg: p50
                    - name: branch.time_to_pr
                      agg: avg
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2023-06-29'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Post Metrics Api V2 Measurements Post
                type: array
                items:
                  $ref: '#/components/schemas/MetricsResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal server error
        '504':
          description: Gateway Timeout
  /api/v2/measurements/export:
    post:
      tags:
        - Measurements V2
      summary: Export Metrics
      description: |-
        Export V2 metrics endpoint

        This API can be used in order to export metrics V2 data in CSV/JSON format.
      operationId: export_metrics_api_v2_measurements_export_post
      parameters:
        - required: false
          schema:
            allOf:
              - $ref: '#/components/schemas/ExporterFileFormats'
            default: csv
          name: file_format
          in: query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExportMetricsPayload'
            examples:
              example1:
                summary: Get metrics with time ranges
                description: ''
                value:
                  group_by: organization
                  roll_up: custom
                  requested_metrics:
                    - name: branch.computed.cycle_time
                      agg: p75
                    - name: releases.count
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2022-05-29'
                    - after: '2022-05-30'
                      before: '2022-06-05'
                    - after: '2022-06-06'
                      before: '2022-06-12'
                    - after: '2022-06-13'
                      before: '2022-06-19'
              example2:
                summary: Get metrics with weekly rollup
                description: ''
                value:
                  group_by: organization
                  roll_up: 1w
                  requested_metrics:
                    - name: branch.computed.cycle_time
                      agg: p75
                    - name: branch.computed.cycle_time
                      agg: avg
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2022-06-29'
              example3:
                summary: Get metrics for specific repository
                description: ''
                value:
                  group_by: organization
                  roll_up: 1d
                  repository_ids:
                    - 456801317
                    - 1235235
                  requested_metrics:
                    - name: branch.time_to_prod
                      agg: p50
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2022-06-29'
              example4:
                summary: Get metrics for specific teams
                description: ''
                value:
                  group_by: team
                  roll_up: 1mo
                  team_ids:
                    - 5273
                    - 58
                  requested_metrics:
                    - name: branch.time_to_prod
                      agg: p50
                    - name: branch.time_to_pr
                      agg: avg
                  time_ranges:
                    - after: '2022-05-27'
                      before: '2023-06-29'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportMeasurementResponse'
        '202':
          description: Request to create report is accepted, but not ready yet
        '204':
          description: No Content. Does not exist or has expired
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/services/:
    get:
      tags:
        - services
      summary: Get Services
      description: Services API endpoint returns a list of services.
      operationId: get_services_api_v1_services__get
      parameters:
        - description: Repository ID to filter by. Return a list of all services, where this repository is presented
          required: false
          schema:
            title: Repository ID
            exclusiveMinimum: false
            type: integer
            description: Repository ID to filter by. Return a list of all services, where this repository is presented
          name: repository_id
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServicesResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/services/{service_id}:
    get:
      tags:
        - services
      summary: Get Service
      description: Services API endpoint returns a single service by id.
      operationId: get_service_api_v1_services__service_id__get
      parameters:
        - description: Service object ID
          required: true
          schema:
            title: Service ID
            type: integer
            description: Service object ID
          name: service_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/incidents/{provider_id}:
    get:
      tags:
        - incidents
      summary: Get Incident
      description: '**Get Incident**'
      operationId: get_incident_api_v1_incidents__provider_id__get
      parameters:
        - description: The unique identifier in the PM provider
          required: true
          schema:
            title: Provider ID
            minLength: 1
            type: string
            description: The unique identifier in the PM provider
          name: provider_id
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetIncidentResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
    delete:
      tags:
        - incidents
      summary: Delete Incident
      description: '**Delete Incident**'
      operationId: delete_incident_api_v1_incidents__provider_id__delete
      parameters:
        - description: The unique identifier in the PM provider
          required: true
          schema:
            title: Provider ID
            minLength: 1
            type: string
            description: The unique identifier in the PM provider
          name: provider_id
          in: path
      responses:
        '200':
          description: Successful Response
        '204':
          description: Successful Response
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
    patch:
      tags:
        - incidents
      summary: Update Incident
      description: '**Update Incident**'
      operationId: patch_incident_api_v1_incidents__provider_id__patch
      parameters:
        - description: The unique identifier in the PM provider
          required: true
          schema:
            title: Provider ID
            minLength: 1
            type: string
            description: The unique identifier in the PM provider
          name: provider_id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateIncidentRequestModel'
            examples:
              example1:
                summary: Update the incident
                description: ''
                value:
                  title: This is changed title
                  started_at: 2023-05-03 18:00
                  repository_urls:
                    - https://github.com/myorg/repo2.git
        required: true
      responses:
        '200':
          description: Successful Response
        '204':
          description: Successful Response
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/incidents/search:
    post:
      tags:
        - incidents
      summary: Search Incidents
      description: '**Search Incidents**'
      operationId: search_incidents_api_v1_incidents_search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchIncidentsRequestModel'
            examples:
              example1:
                summary: Opened incidents after a date
                description: ''
                value:
                  limit: 50
                  issued_at:
                    after: '2021-12-01'
                  statuses:
                    - open
              example2:
                summary: Uncompleted incidents between dates at specific repo
                description: ''
                value:
                  limit: 50
                  issued_at:
                    after: '2021-01-01'
                    before: '2022-12-31'
                  repository_urls:
                    - https://github.com/myorg/website.git
                  statuses:
                    - open
                    - in-progress
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchIncidentsResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/incidents:
    post:
      tags:
        - incidents
      summary: Create Incident
      description: '**Create Incident**'
      operationId: post_incident_api_v1_incidents_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIncidentRequestModel'
            examples:
              example1:
                summary: Create an incident
                description: ''
                value:
                  provider_id: provider_internal_id1
                  http_url: http://myprovider.io/1
                  title: This is critical production bug
                  issued_at: '2019-09-26T07:58:30.996'
                  teams:
                    - Team A
                    - Team B
                  repository_urls:
                    - https://github.com/myorg/repo1.git
                    - https://github.com/myorg/repo2.git
        required: true
      responses:
        '200':
          description: Successful Response
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/cycle-time-stages:
    post:
      summary: Post Cycle Time Stage
      operationId: post_cycle_time_stage_api_v1_cycle_time_stages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCycleTimeStageRequestModel'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCycleTimeStageResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
      deprecated: true
  /api/v1/health:
    get:
      summary: Health
      description: |-
        :route: GET /health
        :return: message OK if success
      operationId: health_api_v1_health_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal Server Error
        '504':
          description: Gateway Timeout
  /api/v1/report/event:
    post:
      tags:
        - Report Event
      summary: Post Custom Metrics
      description: |-
        Post report event
        This API allows you to report events in order to be able to query later in LinearB platform
      operationId: post_custom_metrics_api_v1_report_event_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostCustomMetricModel'
            examples:
              example1:
                summary: Example with all values
                description: ''
                value:
                  source: gitstream
                  timestamp: '2022-03-13 08:07:12.613'
                  metric_name: ran_cm
                  value: '2.5'
                  entity:
                    pr_url: https://github.com/hello/world/pull/1731
                  tags:
                    my_tag: my_value
              example2:
                summary: Example with commit_sha and pr url
                description: ''
                value:
                  timestamp: '2022-03-13 08:07:12.613'
                  metric_name: ran_cm
                  entity:
                    pr_url: https://github.com/testorg/testrepo/1234
                    commit_sha: my_commit_sha
              example3:
                summary: Example with timestamp that is EPOCH
                description: ''
                value:
                  timestamp: 1706622966150
                  metric_name: ran_cm
                  entity:
                    pr_url: https://github.com/linear-b/linweb/pull/1731
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostCustomMetricResponseModel'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '405':
          description: Method Not Allowed
        '422':
          description: Validation Error
        '500':
          description: Internal server error
        '504':
          description: Gateway Timeout
components:
  schemas:
    ContributorModel:
      title: ContributorModel
      required:
        - id
        - name
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
        parent_id:
          title: Parent Id
          type: integer
        provider_id:
          title: Provider Id
          type: string
        roles:
          title: Roles
          type: array
          items:
            type: object
    ContributorPartialResponseModel:
      title: ContributorPartialResponseModel
      required:
        - id
        - name
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
      description: 'Contributors response model with partial data. '
    CreateCycleTimeStageRequestModel:
      title: CreateCycleTimeStageRequestModel
      required:
        - repo_url
        - head_sha
        - event_time
        - stage_id
      type: object
      properties:
        repo_url:
          title: Repository url
          pattern: ^https://[a-zA-Z0-9./+^@_%-]{15,250}$
          type: string
        head_sha:
          title: Head commit sha
          pattern: ^[0-9a-z]{5,40}$
          type: string
        event_time:
          title: Epoch time
          type: number
        stage_id:
          title: Stage id
          pattern: ^[a-zA-Z0-9-_]{2,32}$
          type: string
      example:
        repo_url: https://github.com/owner/my-repo.git
        head_sha: q1w2e3r4t5y6u7i8o
        event_time: 1586944173.95799
        stage_id: release
    CreateCycleTimeStageResponseModel:
      title: CreateCycleTimeStageResponseModel
      required:
        - request_id
      type: object
      properties:
        request_id:
          title: Request Id
          type: string
    CreateDeploymentRequestModel:
      title: CreateDeploymentRequestModel
      required:
        - repo_url
        - ref_name
      type: object
      properties:
        repo_url:
          title: Repository url
          pattern: ^https://[a-zA-Z0-9./+^@_%-]{15,250}$
          type: string
          description: should be a qualified Git URL
        ref_name:
          title: Ref name of the release, accepts any Git ref                           i.e. commit short or long sha or tag name
          pattern: ^[!\"#\$%&\'()+,\-0-9;<=>\@A-Z\]_`a-z{|}.]{5,40}$
          type: string
        timestamp:
          title: Timestamp ISO 8601 format
          type: string
          format: date-time
        stage:
          title: Deployment stage
          pattern: ^[a-zA-Z0-9-_]{2,32}$
          type: string
          default: release
        services:
          title: Services list
          type: array
          items:
            type: string
    CreateDeploymentResponseModel:
      title: CreateDeploymentResponseModel
      required:
        - request_id
      type: object
      properties:
        request_id:
          title: Request Id
          type: string
    CreateIncidentRequestModel:
      title: CreateIncidentRequestModel
      required:
        - provider_id
        - http_url
        - title
        - issued_at
      type: object
      properties:
        provider_id:
          title: Provider Id
          maxLength: 255
          minLength: 1
          type: string
          description: The unique identifier in the PM provider
        http_url:
          title: Http Url
          maxLength: 512
          pattern: ^(http|https)://[a-zA-Z0-9./+^@_%-]{5,250}$
          type: string
          description: Trace back URL to the PM provider URL/key should                                        open the incident in the PM provider
        title:
          title: Title
          maxLength: 255
          minLength: 1
          type: string
          description: The title of the incident
        issued_at:
          title: Issued At
          type: string
          description: The incident was open at this specific time, can be ISO8601 or EPOCH timestmap
        started_at:
          title: Started At
          type: string
          description: The incident was started at this specific time, can be ISO8601 or EPOCH timestmap
        ended_at:
          title: Ended At
          type: string
          description: The incident was resolved at this specific time, can be ISO8601 or EPOCH timestmap
        git_ref:
          title: Git Ref
          pattern: ^[!\"#\$%&\'()+,\-0-9;<=>\@A-Z\]_`a-z{|}.]{5,40}$
          type: string
          description: The git reference of the release, i.e.                                                 commit short or long sha or tag name
        teams:
          title: Teams
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of LinearB teams names related to this incident
        services:
          title: Services
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of LinearB services monitoring this incident
        repository_urls:
          title: Repository Urls
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of repos urls related to this incident
      description: |-
        This model ovverides default functionality and remove nullable field from dict object

        :param BaseModel: the BaseModel
    DateFilter:
      title: DateFilter
      type: object
      properties:
        before:
          title: Before
          type: string
          description: Before date
        after:
          title: After
          type: string
          description: After date
      description: |-
        This model ovverides default functionality and remove nullable field from dict object

        :param BaseModel: the BaseModel
    DeploymentsSortByEnum:
      title: DeploymentsSortByEnum
      enum:
        - published_at
      type: string
      description: An enumeration.
    DeploymentsSortDirEnum:
      title: DeploymentsSortDirEnum
      enum:
        - asc
        - desc
      type: string
      description: An enumeration.
    ExportMeasurementResponse:
      title: ExportMeasurementResponse
      required:
        - report_url
        - detail
      type: object
      properties:
        report_url:
          title: Report Url
          type: string
        detail:
          title: Detail
          type: string
    ExportMetricsPayload:
      title: ExportMetricsPayload
      required:
        - requested_metrics
        - time_ranges
      type: object
      properties:
        group_by:
          allOf:
            - $ref: '#/components/schemas/GroupByEnum'
          description: Field to group by. One of organization, team, contributor, repository
          default: organization
        requested_metrics:
          title: Requested Metrics
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/RequestedMetric'
          description: Array of metrics to fetch.
        roll_up:
          allOf:
            - $ref: '#/components/schemas/RollupEnum'
          default: custom
        contributor_ids:
          title: Contributor Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Array of contributors to filter by.
        repository_ids:
          title: Repository Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Array of repositories to filter by.
        team_ids:
          title: Team Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Should be passed when requesting group_by equals team.
        service_ids:
          title: Service Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Array of services to filter by.
        limit:
          title: Limit
          exclusiveMinimum: false
          type: integer
          description: Max amount of objects in the response. When request for multiple contributors, teams or repositories, limit should be more or equal of amount of passed ids (or data will be returned partially)
        offset:
          title: Offset
          minimum: 0
          type: integer
          description: Used for pagination, defines the offset for the query.
        order_by:
          title: Order By
          type: string
          description: Field name to order by.
        order_dir:
          allOf:
            - $ref: '#/components/schemas/SortDirectionEnum'
          description: Ordering direction. Default is asc.
          default: asc
        time_ranges:
          title: Time Ranges
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/TimeRangeModel'
          description: Should always exist
        labels:
          title: Labels
          maxItems: 3
          type: array
          items:
            type: string
          description: 'If the grouping is based on labels, the results will be grouped according to the specified labels. For other group by values, the results will be filtered based on the provided labels. '
        beautified:
          title: Beautified
          type: boolean
          description: Defaults to false, will format the data in case of CSV to a more readable format
          default: false
    ExporterFileFormats:
      title: ExporterFileFormats
      enum:
        - csv
        - json
      description: An enumeration.
    GetDeploymentsResponseModel:
      title: GetDeploymentsResponseModel
      required:
        - total
        - items
      type: object
      properties:
        total:
          title: Total
          type: integer
        items:
          title: Items
          type: array
          items:
            type: object
    GetIncidentResponseModel:
      title: GetIncidentResponseModel
      required:
        - provider_id
        - http_url
        - title
        - issued_at
        - status
      type: object
      properties:
        provider_id:
          title: Provider Id
          type: string
        http_url:
          title: Http Url
          type: string
        title:
          title: Title
          type: string
        issued_at:
          title: Issued At
          type: string
        started_at:
          title: Started At
          type: string
        ended_at:
          title: Ended At
          type: string
        git_ref:
          title: Git Ref
          type: string
        teams:
          title: Teams
          type: array
          items:
            type: object
        services:
          title: Services
          type: array
          items:
            type: object
        repositories:
          title: Repositories
          type: array
          items:
            type: object
        status:
          title: Status
          type: string
      description: |-
        This model ovverides default functionality and remove nullable field from dict object

        :param BaseModel: the BaseModel
    GetMetricsPayloadModel:
      title: GetMetricsPayloadModel
      required:
        - requested_metrics
        - time_ranges
      type: object
      properties:
        group_by:
          allOf:
            - $ref: '#/components/schemas/GroupByEnum'
          description: Field to group by. One of organization, team, contributor, repository
          default: organization
        requested_metrics:
          title: Requested Metrics
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/RequestedMetric'
          description: Array of metrics to fetch.
        roll_up:
          allOf:
            - $ref: '#/components/schemas/RollupEnum'
          default: custom
        contributor_ids:
          title: Contributor Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Array of contributors to filter by.
        repository_ids:
          title: Repository Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Array of repositories to filter by.
        team_ids:
          title: Team Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Should be passed when requesting group_by equals team.
        service_ids:
          title: Service Ids
          minItems: 1
          type: array
          items:
            type: integer
          description: Array of services to filter by.
        limit:
          title: Limit
          exclusiveMinimum: false
          type: integer
          description: Max amount of objects in the response. When request for multiple contributors, teams or repositories, limit should be more or equal of amount of passed ids (or data will be returned partially)
        offset:
          title: Offset
          minimum: 0
          type: integer
          description: Used for pagination, defines the offset for the query.
        order_by:
          title: Order By
          type: string
          description: Field name to order by.
        order_dir:
          allOf:
            - $ref: '#/components/schemas/SortDirectionEnum'
          description: Ordering direction. Default is asc.
          default: asc
        time_ranges:
          title: Time Ranges
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/TimeRangeModel'
          description: Should always exist
        labels:
          title: Labels
          maxItems: 3
          type: array
          items:
            type: string
          description: 'If the grouping is based on labels, the results will be grouped according to the specified labels. For other group by values, the results will be filtered based on the provided labels. '
    GetTeamsFullResponseModel:
      title: GetTeamsFullResponseModel
      required:
        - total
        - items
      type: object
      properties:
        total:
          title: Total
          type: integer
        items:
          title: Items
          type: array
          items:
            $ref: '#/components/schemas/TeamModel'
      description: 'Teams response model with full data. '
    GetTeamsPartialResponseModel:
      title: GetTeamsPartialResponseModel
      required:
        - total
        - items
      type: object
      properties:
        total:
          title: Total
          type: integer
        items:
          title: Items
          type: array
          items:
            $ref: '#/components/schemas/TeamPartialResponseModel'
      description: 'Teams response model with partial data. '
    GroupByEnum:
      title: GroupByEnum
      enum:
        - organization
        - contributor
        - team
        - custom_metric
        - repository
        - label
      type: string
      description: An enumeration.
    IncidentPartial:
      title: IncidentPartial
      required:
        - provider_id
        - http_url
        - title
        - issued_at
        - status
      type: object
      properties:
        provider_id:
          title: Provider Id
          type: string
        http_url:
          title: Http Url
          type: string
        title:
          title: Title
          type: string
        issued_at:
          title: Issued At
          type: string
        started_at:
          title: Started At
          type: string
        ended_at:
          title: Ended At
          type: string
        git_ref:
          title: Git Ref
          type: string
        teams:
          title: Teams
          type: array
          items:
            type: object
        services:
          title: Services
          type: array
          items:
            type: object
        repositories:
          title: Repositories
          type: array
          items:
            type: object
        status:
          title: Status
          type: string
      description: |-
        This model ovverides default functionality and remove nullable field from dict object

        :param BaseModel: the BaseModel
    IncidentStatuses:
      title: IncidentStatuses
      enum:
        - open
        - in-progress
        - closed
        - deleted
      type: string
      description: An enumeration.
    IncidentsSortByEnum:
      title: IncidentsSortByEnum
      enum:
        - issued_at
        - started_at
        - ended_at
      type: string
      description: An enumeration.
    MetricsAggregationEnum:
      title: MetricsAggregationEnum
      enum:
        - p75
        - avg
        - p50
        - default
      type: string
      description: An enumeration.
    MetricsNamesEnum:
      title: MetricsNamesEnum
      enum:
        - branch.time_to_pr
        - branch.time_to_approve
        - branch.time_to_merge
        - branch.time_to_review
        - branch.review_time
        - branch.time_to_prod
        - branch.computed.cycle_time
        - pr.merged
        - pr.merged.size
        - pr.new
        - pr.review_depth
        - pr.reviews
        - commit. olved.repos.count
        - pr.merged.without.review.count
        - releases.count
        - commit.total.count
        - commit.activity.new_work.count
        - commit.activity.rework.count
        - commit.activity.refactor.count
        - commit.total_changes
        - commit.activity_days
        - branch.state.computed.done
        - pm.mttr
        - pm.cfr.issues.done
        - branch.state.active
        - pr.maturity_ratio
      type: string
      description: An enumeration.
    MetricsResponseModel:
      title: MetricsResponseModel
      required:
        - after
        - before
        - metrics
      type: object
      properties:
        after:
          title: After
          type: string
        before:
          title: Before
          type: string
        metrics:
          title: Metrics
          type: array
          items:
            type: object
    PostCustomMetricModel:
      title: PostCustomMetricModel
      required:
        - metric_name
        - timestamp
      type: object
      properties:
        metric_name:
          title: Metric Name
          maxLength: 255
          minLength: 1
          type: string
          description: The metric you are reporting
        timestamp:
          title: Timestamp
          anyOf:
            - type: string
            - type: integer
          description: Timestamp at which the event happened
        value:
          title: Value
          type: number
          description: Float value representing metric
        source:
          title: Source
          type: string
          description: Source of the event
        entity:
          title: Entity
          type: object
          description: Entity defining the branch/pr url being reported
          default: {}
        tags:
          title: Tags
          type: object
          description: Any tags that can help identify the event later on
          default: {}
    PostCustomMetricResponseModel:
      title: PostCustomMetricResponseModel
      required:
        - message
      type: object
      properties:
        message:
          title: Message
          type: string
        event_uuid:
          title: Event Uuid
          type: string
    RepositoryPaths:
      title: RepositoryPaths
      required:
        - id
        - paths
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
        paths:
          title: Paths
          type: array
          items:
            type: string
    RequestedMetric:
      title: RequestedMetric
      required:
        - name
      type: object
      properties:
        name:
          title: Name
          anyOf:
            - $ref: '#/components/schemas/MetricsNamesEnum'
            - type: string
        agg:
          allOf:
            - $ref: '#/components/schemas/MetricsAggregationEnum'
          default: default
        filters:
          title: Filters
          type: object
    RollupEnum:
      title: RollupEnum
      enum:
        - 1d
        - 1w
        - 1mo
        - custom
      type: string
      description: An enumeration.
    SearchIncidentsRequestModel:
      title: SearchIncidentsRequestModel
      type: object
      properties:
        repository_urls:
          title: Repository Urls
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of repos urls related to this incident
        services:
          title: Services
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of LinearB services monitoring this incident
        teams:
          title: Teams
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of LinearB teams names related to this incident
        statuses:
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/IncidentStatuses'
          description: The list of statuses of the incident
        sort_by:
          allOf:
            - $ref: '#/components/schemas/IncidentsSortByEnum'
          default: issued_at
        sort_dir:
          allOf:
            - $ref: '#/components/schemas/SortDirectionEnum'
          default: desc
        issued_at:
          title: Issued At
          allOf:
            - $ref: '#/components/schemas/DateFilter'
          description: The incident was open at this specific time
        started_at:
          title: Started At
          allOf:
            - $ref: '#/components/schemas/DateFilter'
          description: The incident was started at this specific time
        ended_at:
          title: Ended At
          allOf:
            - $ref: '#/components/schemas/DateFilter'
          description: The incident was resolved at this specific time
        limit:
          title: Limit
          maximum: 100
          exclusiveMinimum: false
          type: integer
          default: 25
        offset:
          title: Offset
          minimum: 0
          type: integer
          default: 0
      description: |-
        This model ovverides default functionality and remove nullable field from dict object

        :param BaseModel: the BaseModel
    SearchIncidentsResponseModel:
      title: SearchIncidentsResponseModel
      required:
        - total
        - items
      type: object
      properties:
        total:
          title: Total
          type: integer
        items:
          title: Items
          type: array
          items:
            $ref: '#/components/schemas/IncidentPartial'
      description: |-
        This model ovverides default functionality and remove nullable field from dict object

        :param BaseModel: the BaseModel
    ServiceModel:
      title: ServiceModel
      required:
        - id
        - name
        - paths
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
        paths:
          title: Paths
          type: array
          items:
            $ref: '#/components/schemas/RepositoryPaths'
      description: 'Model for service object after processing the raw response of the services API (linpr) '
    ServicesResponse:
      title: ServicesResponse
      required:
        - total
        - items
      type: object
      properties:
        total:
          title: Total
          type: integer
        items:
          title: Items
          type: array
          items:
            $ref: '#/components/schemas/ServiceModel'
      description: |-
        Services endpoint response model.
        We modify the output of linpr API for the final users. We return only id, names and paths for services, also include
        repositories names in the paths strategies
    SortDirectionEnum:
      title: SortDirectionEnum
      enum:
        - asc
        - desc
      type: string
      description: An enumeration.
    TeamModel:
      title: TeamModel
      required:
        - id
        - organization_id
        - name
        - created_at
      type: object
      properties:
        id:
          title: Id
          type: integer
        organization_id:
          title: Organization Id
          type: integer
        name:
          title: Name
          type: string
        created_at:
          title: Created At
          type: string
        initials:
          title: Initials
          type: string
        color:
          title: Color
          type: string
        updated_at:
          title: Updated At
          type: string
        deleted_at:
          title: Deleted At
          type: string
        extra:
          title: Extra
          type: object
        established_at:
          title: Established At
          type: string
        project_id:
          title: Project Id
          type: integer
        parent_id:
          title: Parent Id
          type: integer
        provider_id:
          title: Provider Id
          type: string
        contributors:
          title: Contributors
          type: array
          items:
            $ref: '#/components/schemas/ContributorModel'
    TeamPartialResponseModel:
      title: TeamPartialResponseModel
      required:
        - id
        - name
      type: object
      properties:
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
        contributors:
          title: Contributors
          type: array
          items:
            $ref: '#/components/schemas/ContributorPartialResponseModel'
      description: 'Team response model with partial data. '
    TimeRangeModel:
      title: TimeRangeModel
      required:
        - before
        - after
      type: object
      properties:
        before:
          title: Before
          type: string
        after:
          title: After
          type: string
    UpdateIncidentRequestModel:
      title: UpdateIncidentRequestModel
      type: object
      properties:
        title:
          title: Title
          maxLength: 255
          minLength: 1
          type: string
          description: The title of the incident
          default: unset
        issued_at:
          title: Issued At
          type: string
          description: The incident was open at this specific time, can be ISO8601 or EPOCH timestmap
          default: unset
        started_at:
          title: Started At
          type: string
          description: The incident was started at this specific time, can be ISO8601 or EPOCH timestmap
          default: unset
        ended_at:
          title: Ended At
          type: string
          description: The incident was resolved at this specific time, can be ISO8601 or EPOCH timestmap
          default: unset
        git_ref:
          title: Git Ref
          pattern: ^[!\"#\$%&\'()+,\-0-9;<=>\@A-Z\]_`a-z{|}.]{5,40}$
          type: string
          description: The git reference of the release,                                                i.e. commit short or long sha or tag name
          default: unset
        teams:
          title: Teams
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of LinearB teams names related to this incident
          default: []
        services:
          title: Services
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of LinearB services monitoring this incident
          default: []
        repository_urls:
          title: Repository Urls
          minItems: 1
          uniqueItems: true
          type: array
          items:
            type: string
          description: The list of repos urls related to this incident
          default: []
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: x-api-key
tags:
  - name: deployments
    description: Deployment Tracking API
  - name: Measurements V2
    description: Measurements V2 API
  - name: teams
    description: Teams API
  - name: services
    description: Services API
  - name: incidents
    description: Incidents API
  - name: Report Event
    description: Report Event
security:
  - APIKeyHeader: []